services:

  postgres:
    image: postgres:17
    container_name: tiendatech_postgres
    restart: always

    environment:
      POSTGRES_DB: ${DOCKER_POSTGRES_DB}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: tiendatech_app
    restart: always

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    env_file:
      - .env

    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data: