spring.application.name=TiendaTechV10
spring.datasource.url=jdbc:postgresql://localhost:5432/TiendaTechV10
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.proc.param_null_passing=true
app.upload-root=C:/Users/usuario/Documents/Universidad/Proyecto Tienda Tech/V3/Tienda_Tech/Tienda_Tech/uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB