spring.application.name=TiendaTechV12
spring.datasource.url=jdbc:postgresql://localhost:5432/TiendaTechV12
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.proc.param_null_passing=true
app.upload-root=${APP_UPLOAD_ROOT:${user.dir}/uploads}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.jpa.properties.hibernate.default_schema=public
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Todo para validar correo
# SMTP (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Un correito
spring.mail.password=Contraseña de aplicativo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OTP (t� los usas en OtpService/CacheConfig)
otp.ttl-minutes=10
otp.length=6
otp.resend.cooldown-seconds=60
otp.rate.max-per-15min=3